CREATE TABLE GOODS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    SHOP_ID     BIGINT,
    NAME        VARCHAR(100),
    DESCRIPTION VARCHAR(1024),
    DETAILS     TEXT,
    IMG_URL     VARCHAR(1024),
    PRICE       DECIMAL,
    STOCK       INT       NOT NULL DEFAULT 0,
    STATUS      VARCHAR(16),
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT NOW()
)