CREATE TABLE `ORDER`
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID     BIGINT,
    GOODS_ID    BIGINT,
    NUMBER      INT,
    TOTAL_PRICE DECIMAL,
    STATUS      VARCHAR(16),
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT NOW()
)